name = "Elastic"
uuid = "8d3b6ab6-2a4c-459f-a8e0-67b5a5ac360f"
authors = ["David James <davidabraham@ucla.edu>"]
version = "0.1.0"

[deps]
BlockingMethod = "d9bca9eb-1e72-4788-bb56-3426fa9acbbd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Printf = "1.11.0"
